INSERT INTO LESSORS(ID, FIRST_NAME, LAST_NAME) VALUES (1, 'John', 'Doe');
INSERT INTO LESSEES(ID, FIRST_NAME, LAST_NAME) VALUES (1, 'John', 'Do');
INSERT INTO PLACES(ID, NAME, AREA, UNIT_PRICE) VALUES (1, 'House', 1, 1);